### ISSUE TITLE
[Bug] Discounted food items are still being processed in original (non-discounted) price

### ISSUE THREAD

**Issue by tien-thanh-hua** [khengyun/FFood-shop#107]
### Description

The discounted food items are only visually displayed as discounted, while the backend logic still treats them as non-discounted.

# Note
Someone broke my cart UI while fixing merge conflicts, goddamn it I have to fix it again

![image](https://github.com/khengyun/FFood-shop/assets/88323009/c57ea3eb-0e4f-4a8f-ae35-82d1b5b21775)
![image](https://github.com/khengyun/FFood-shop/assets/88323009/bbec1513-5398-45b1-9d8c-191e5f3a2ace)

### Severity

Critical

### Steps to reproduce

1. Add a discounted food item to cart
2. Open cart modal
3. Click on Checkout button
4. Place an order
5. Log in to Admin Dashboard
6. Click on Orders tab
7. Verify the order's "discounted" item not being discounted 

### Expected behavior (Optional)

The correctly discounted food items should be visible to the end user at all times and the actual order total must also be properly calculated with such discounted items in mind.

### Operating system

Windows

### Operating system version (Optional)

11 22H2

### Browser

Microsoft Edge

### Browser Version (Optional)

118.0.2088.69

### Additional context (Optional)

I think the discount implementation should be completely done in backend, meaning foodPrice = food.foodPrice - (food.foodPrice * food.discountPercent / 100) should be put in the Java servlets instead of JSP pages (the number and currency format can stay in frontend).

**Comment by khengyun** [comment]
👋 @tien-thanh-hua
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
