### ISSUE TITLE
[Bug] not have "disable" class for deleteBtn and filter  for USER tab

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#111]
### Description

fix bug not have disable for delete button when click outside a row
add filter for Usertab
![image](https://github.com/khengyun/FFood-shop/assets/29297028/42963ff1-59be-40f3-a0b3-3e8feb3266b4)

### Severity

Major

### Steps to reproduce

1. fix not have disable for delete button
2. add filter for user tab

### Operating system

Windows

### Operating system version (Optional)

11

### Browser

Microsoft Edge

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
