### ISSUE TITLE
[Feature] login with face recognition

### ISSUE THREAD

**Issue by khengyun** [khengyun/FFood-shop#115]
### Problem description

I don't know what I was thinking, but with the capabilities and what I had set up for the previous functionality. then facial login is possible for this website.

![image](https://github.com/khengyun/FFood-shop/assets/78076796/6f826c95-b920-4dde-91c3-5dd0b65eb251)

### Preferred solution

I have researched many related methods. Maybe I'll add this functionality if it's stable.

**Comment by khengyun** [comment]
👋 @khengyun
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.

**Comment by quzanh1130** [comment]
I think we need to do it in late of this project, so we need to change it to low priority.
