### ISSUE TITLE
Home page theming issues after modifying theme.css

### ISSUE THREAD

**Issue by tien-thanh-hua** [khengyun/FFood-shop#25]
# **Description**
Many HTML elements using Bootstrap color classes have their colors changed, which negatively impacts the overall look and feel of the website.

# **Reproduction steps**

1. Go to home page ("/")

# **Expected behavior**
Unpleasant color contrast on multiple elements using primary color background (hero banner), danger color background (discount tags)

# **Screenshots**

![Screenshot 2023-10-15 110033](https://github.com/khengyun/FFood-shop/assets/88323009/5045ee3f-5d94-4b1b-98a3-e98804d637a1)
**_Hero banner with low color contrast_**

![Screenshot 2023-10-15 110133](https://github.com/khengyun/FFood-shop/assets/88323009/e34138ee-2096-479d-b9c5-dde3da5160ce)
**_Discount tags with low color contrast_**

# **Devices**

## **Desktop:**
 - OS: Windows 11 22H2 (build 22621.2428)
 - Browser: Microsoft Edge
 - Version: 117.0.2045.60

# **Additional context**
This problem can be fixed by configuring classes in theme.css and/or using other background color classes for the affected HTML elements.

**Comment by khengyun** [comment]
👋 @tien-thanh-hua
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.

**Comment by khengyun** [comment]
about this issue.
I have a suggestion about contrast.
Can use shecodes to check the theme
https://palettes.shecodes.io/
<img width="1195" alt="image" src="https://github.com/khengyun/FFood-shop/assets/78076796/59aa25fb-5e0d-4afe-96a8-3571df9daffd">
