### ISSUE TITLE
Status toast messages for admin actions (Add, Update, Delete)

### ISSUE THREAD

**Issue by tien-thanh-hua** [khengyun/FFood-shop#26]
# **Related problem**
It's hard to figure out whether an action is successful, especially if the action requires a page reload, such as:
- Adding/removing food items from the cart
- Adding/updating/deleting an item from the database
- Placing an order as a customer
- Updating a user's own personal info or login password

# **Desirable solution**
A similar implementation to [quzanh1130's toast messages](https://github.com/quzanh1130/Toast_message) could be used. I'll do some extra UX research and add improvements if necessary.

## **Additional context**
Due to my unfamiliarity with AJAX techniques, it might be difficult for me to trigger toast messages without reloading a page. But I'll do my best not to be overreliant on using parameters and attributes to trigger the toast messages post-reload.

**Comment by khengyun** [comment]
👋 @tien-thanh-hua
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
