### ISSUE TITLE
🐽 sql file format error 

### ISSUE THREAD

**Issue by khengyun** [khengyun/FFood-shop#28]
**Describe the bug**
The content in the [ffood_insert_row.sql](https://github.com/khengyun/FFood-shop/blob/0a7473f30e3a731daf3b03e17f2a3339f2bcf87a/db_scripts/ffood_insert_row.sql) file contains inappropriate characters.

**Screenshots**
<img width="1280" alt="image" src="https://github.com/khengyun/FFood-shop/assets/78076796/3eaea97d-b4a8-45bd-969b-447282f4aa9d">

**Desktop (please complete the following information):**
 - OS: window 11
 - sql server 2019
 - Version : 0a7473f30e3a731daf3b03e17f2a3339f2bcf87a

**Comment by khengyun** [comment]
👋 @khengyun
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.

**Comment by quzanh1130** [comment]
I have fixed this error. Thanks for your contribute
