### ISSUE TITLE
Add google map location

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#29]
**Is your feature request related to a problem? Please describe.**
Help  customer know where our shop location

**Describe the solution you'd like**
Add gg map location.

**Additional context**
``` javascript
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3817.1930812065903!2d105.73423656511284!3d10.013112967960716!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31a0882139720a77%3A0x3916a227d0b95a64!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBGUFQgQ-G6p24gVGjGoQ!5e0!3m2!1sen!2s!4v1697447209454!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
```

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.

**Comment by quzanh1130** [comment]
I have add it

id : 56b89cdeb9a2abc129bcc820456a8027045a185f
