### ISSUE TITLE
Facebook and zalo contact!!!

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#30]
**Is your feature request related to a problem? Please describe.**
Add Facebook,  zalo and email contact to support customer

**Describe the solution you'd like**
Add Facebook, zalo icon
New email: f[food.shop.cantho@gmail.com](mailto:food.shop.cantho@gmail.com)

![image](https://github.com/khengyun/FFood-shop/assets/29297028/58b25c70-ff6c-4531-b73d-bec94f506e37)

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.

**Comment by quzanh1130** [comment]
complete
