### ISSUE TITLE
Notification how many foods in cart icon

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#31]
**Is your feature request related to a problem? Please describe.**
Add badge notification on cart icon

**Additional context**
Link: [Notification](https://getbootstrap.com/docs/5.3/components/badge/#examples)

![image](https://github.com/khengyun/FFood-shop/assets/29297028/ec621f45-76a3-4651-8ddb-ea7aac598413)

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
