### ISSUE TITLE
Enhance homepage interface

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#32]
**Is your feature request related to a problem? Please describe.**
Add popular food section and more food button

**Describe the solution you'd like**
Add a section for popular food and a button to show more food because have 132 food in database

![image](https://github.com/khengyun/FFood-shop/assets/29297028/56192dba-c29a-444a-874e-c80f888dd73a)

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
