### ISSUE TITLE
Add rating attribute for Food database object

### ISSUE THREAD

**Issue by tien-thanh-hua** [khengyun/FFood-shop#33]
**Is your feature request related to a problem? Please describe.**
To display the current rating of a food item, the rating data must be retrieved from the database. Unfortunately, there is no such attribute for the Food items.

**Describe the solution you'd like**
Add an extra attribute for the Food entity, titled "food_rating".

**Comment by khengyun** [comment]
👋 @tien-thanh-hua
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.

**Comment by quzanh1130** [comment]
I have update database
