### ISSUE TITLE
 ❌☠️There are no wrong password warnings, or invalid login information

### ISSUE THREAD

**Issue by khengyun** [khengyun/FFood-shop#35]
**Describe the bug**
There are no wrong password warnings, or invalid login information

**Additional context**
https://github.com/khengyun/FFood-shop/assets/78076796/b24bd8ca-180c-4e47-845b-58fd1f4645a5

**Comment by khengyun** [comment]
👋 @khengyun
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.

**Comment by quzanh1130** [comment]
I have add the nofitication for this, but in future we will use toast message for better interface.

**Comment by khengyun** [comment]
I mean just the notification line below the input box is fine, no need for a  toast message !!

**Comment by khengyun** [comment]
Close the issue only when the bug has been resolved @quzanh1130

**Comment by quzanh1130** [comment]
@khengyun I have fixed it, you need to review it in the main branch. I am just not using "the notification line" and toast message.

**Comment by khengyun** [comment]
Do you mean the fix-error branch?

> @khengyun I have fixed it, you need to review it in the main branch. I am just not using "the notification line" and toast message.

Do you mean the fix-error branch?
