### ISSUE TITLE
Do not have any history order

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#36]
**Describe the bug**
I create a user and order after that, but when I view my order that empty.

**Screenshots**
![image](https://github.com/khengyun/FFood-shop/assets/29297028/0ed0bbe0-1fe5-40e4-9ac6-17ca61078d87)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Edge

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
