### ISSUE TITLE
You can arrange the drag and drop interface on the admin home page

### ISSUE THREAD

**Issue by khengyun** [khengyun/FFood-shop#44]
Feature Description:
![](https://wp.prototypr.io/wp-content/uploads/2019/11/2019-11-27-15-02-13.2019-11-27-15_03_19.gif)

**Comment by khengyun** [comment]
👋 @khengyun
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.

**Comment by tien-thanh-hua** [comment]
Looks cool, but I'll put it on low priority for now. It's nice-to-have, not a must-have thing.
