### ISSUE TITLE
not update pay money when update quantity of cartItem

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#49]
**Describe the bug**
not update pay money when update quantity of cartItem

**Screenshots**
![image](https://github.com/khengyun/FFood-shop/assets/29297028/9c6dc013-db47-47a9-8a69-8e1898a3c747)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Microsoft edge

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
