### ISSUE TITLE
dont have search bar on manage voucher 

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#59]
**Describe the bug**
dont have search bar on manage voucher

**Screenshots**
![image](https://github.com/khengyun/FFood-shop/assets/29297028/ad99ebce-f237-49f6-82b9-2a50efb0f246)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser ms edge

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
