### ISSUE TITLE
Update Log in form with Google Sign-in

### ISSUE THREAD

**Issue by tien-thanh-hua** [khengyun/FFood-shop#67]
# **Problem description**
Logging in manually in 2023 sucks. Especially when almost everyone on the Internet has at least 1 Google account, it makes you wonder why isn't there a "Sign in with Google".

# **Possible solution**
Add a "Log in with Google" button below the default Login button, but above the Signup link. There are some arguments to be made for whether it should be the de facto log-in method, but most Vietnamese (and non-tech people) are accustomed to the traditional layout, so I'll stick with that.

# **Additional information**
- Remove "Keep me logged in/Remember me" toggle (most websites store login info in cookies anyway, this toggle button only hurts UX)
- New redesign may not be 100% based on the image below

![image](https://github.com/khengyun/FFood-shop/assets/88323009/a74c8acd-611c-4153-80a3-aa9fa3d45b3d)

**Comment by khengyun** [comment]
@tien-thanh-hua I've made 1 update to this feature
