### ISSUE TITLE
add previous and next for category of food section

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#73]
### Problem description

add next and previous icon for change the category of food section

### Preferred solution

not have

### Additional context (Optional)

![image](https://github.com/khengyun/FFood-shop/assets/29297028/cf26758c-aee4-4b18-a32d-69aaf4edc811)

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
