### ISSUE TITLE
[Bug] Can't add food by Admin Roles

### ISSUE THREAD

**Issue by HuynhVuGenius** [khengyun/FFood-shop#76]
### Description

When i add food by admin roles nothing happening with database.

### Severity

Critical

### Steps to reproduce

...

### Operating system

Windows

### Operating system version (Optional)

11

### Browser

Microsoft Edge

**Comment by khengyun** [comment]
👋 @HuynhVuGenius
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.

**Comment by tien-thanh-hua** [comment]
@quzanh1130 use this [branch](https://github.com/khengyun/FFood-shop/tree/fix/dashboard/food-management/cannot-add-food), no need to create one
