### ISSUE TITLE
add status and rate star for food cart item

### ISSUE THREAD

**Issue by quzanh1130** [khengyun/FFood-shop#78]
### Problem description

add front end for food cart: rate star and food status

### Preferred solution

![image](https://github.com/khengyun/FFood-shop/assets/29297028/414e4bc8-86f6-486a-b0b1-5c8216bc7baf)

### Alternative solutions (Optional)

no

### Additional context (Optional)

no

**Comment by khengyun** [comment]
👋 @quzanh1130
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
