### ISSUE TITLE
[Bug] The images in the category are not the same size

### ISSUE THREAD

**Issue by HuynhVuGenius** [khengyun/FFood-shop#80]
### Description

when i login in the homepage, i see The images in the category are not the same size

### Severity

Minor

### Steps to reproduce

...

### Operating system

Windows

### Operating system version (Optional)

11

### Browser

Microsoft Edge

**Comment by khengyun** [comment]
👋 @HuynhVuGenius
Thank you for raising an issue. We will will investigate into the matter and get back to you as soon as possible.
Please make sure you have given us as much context as possible.
